/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GifCard: typeof import('./components/GifCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./components/ShareButton.vue')['default']
  }
}
